// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AquariumMVC.Models;

public partial class all_Product
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string P_id { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Img { get; set; }

    [StringLength(30)]
    public string kind { get; set; }

    [StringLength(10)]
    public string type { get; set; }
}