// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AquariumMVC.Models
{
    

    public partial class alldetail
    {
        [Key]
        public int A_id { get; set; }
        public string P_id { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public int? Price { get; set; }
        public int? Amount { get; set; }
        public string Memo { get; set; }
        public string Img { get; set; }
        public string Kind { get; set; }
        public string Type { get; set; }
    }
}
