// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AquariumMVC.Models;

public partial class aquariumwebsiteContext : DbContext
{
    public aquariumwebsiteContext()
    {

    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseSqlServer("Server=LAPTOP-T8KLA4MT;Database=aquarium website;Trusted_Connection=True;MultipleActiveResultSets=true;User ID=sa;Password=1111;TrustServerCertificate=true;");
        }
    }


    public aquariumwebsiteContext(DbContextOptions<aquariumwebsiteContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Device> Device { get; set; }

    public virtual DbSet<Feeds> Feeds { get; set; }

    public virtual DbSet<Fish> Fish { get; set; }

    public virtual DbSet<Memberdata> Memberdata { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<OrderDetail> OrderDetail { get; set; }

    public virtual DbSet<all_Product> all_Product { get; set; }

    public virtual DbSet<alldetail> AllDetailResults { get; set; }

    public virtual DbSet<Size_priceResult> Size_priceResults { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
        modelBuilder.Entity<alldetail>().HasKey(x => x.A_id); // 明确设置主键
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    
    
}