// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AquariumMVC.Models;

public partial class Fish
{
    [Key]
    public int L_id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string P_id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    [StringLength(30)]
    public string Kind { get; set; }

    [StringLength(10)]
    public string Size { get; set; }

    public int? Price { get; set; }

    public int? Amount { get; set; }

    public string Memo { get; set; }

    [StringLength(30)]
    public string Img { get; set; }
}