// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AquariumMVC.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AquariumMVC.Models
{
    public partial interface IaquariumwebsiteContextProcedures
    {
        Task<List<alldetail>> alldetailAsync(string P_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Size_priceResult>> Size_priceAsync(string P_id, int? A_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
