// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AquariumMVC.Models;

public partial class OrderDetail
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    public string OrderGuid { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Account { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string P_id { get; set; }

    [StringLength(30)]
    public string Name { get; set; }

    public int? Price { get; set; }

    public int? Qty { get; set; }

    public bool? IsApproved { get; set; }

    public int? A_id { get; set; }
}