// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AquariumMVC.Models
{
    public partial class Size_priceResult
    {
        public string P_id { get; set; }
        public int A_id { get; set; }
        public string Size { get; set; }
        public int? Price { get; set; }
        public int? Amount { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
    }
}
